use_frameworks!

platform :ios, '10.0'

target 'SocialSwiftEngineDemo_Example' do
  pod 'SocialSwiftEngineDemo', :path => '../'

  target 'SocialSwiftEngineDemo_Tests' do
    inherit! :search_paths

    
  end
end
